# Assignment

Q1. Create two arrays of six elements. Write the NumPy program to
count the number of instances of a value occurring in one array on
the condition of another array.

    Sample OutputOriginal arrays-
    [ 10 -10 10 -10 -10 10]
    [0.85 0.45 0.9 0.8 0.12 0.6 ]
    Number of instances of a value occurring in one array on the condition of another
    array: 3


In [1]:
import numpy as np
x = np.array([10,-10,10,-10,-10,10])
y = np.array([.85,.45,.9,.8,.12,.6])
print("Original arrays:")
print(x)
print(y)
result = np.sum((x == 10) & (y > .5))
print("\nNumber of instances of a value occurring in one array on the condition of another array:")
print(result)

Original arrays:
[ 10 -10  10 -10 -10  10]
[0.85 0.45 0.9  0.8  0.12 0.6 ]

Number of instances of a value occurring in one array on the condition of another array:
3


Q2. Write the NumPy program to convert a Python dictionary to a
Numpy ndarray ?
    
    Original dictionary-
    {'column0': {'a': 1, 'b': 0.0, 'c': 0.0, 'd': 2.0},
    'column1': {'a': 3.0, 'b': 1, 'c': 0.0, 'd': -1.0},
    'column2': {'a': 4, 'b': 1, 'c': 5.0, 'd': -1.0},
    'column3': {'a': 3.0, 'b': -1.0, 'c': -1.0, 'd': -1.0}}
    Type: <class 'dict'>
    ndarray-
    [[ 1. 0. 0. 2.]
    [ 3. 1. 0. -1.]
    [ 4. 1. 5. -1.]
    [ 3. -1. -1. -1.]]
    Type: <class 'numpy.ndarray'>


In [3]:
import numpy as np
from ast import literal_eval
udict = """{"column0":{"a":1,"b":0.0,"c":0.0,"d":2.0},
   "column1":{"a":3.0,"b":1,"c":0.0,"d":-1.0},
   "column2":{"a":4,"b":1,"c":5.0,"d":-1.0},
   "column3":{"a":3.0,"b":-1.0,"c":-1.0,"d":-1.0}
  }"""
t = literal_eval(udict)
print("\nOriginal dictionary:")
print(t)
print("Type: ",type(t))
result_nparra = np.array([[v[j] for j in ['a', 'b', 'c', 'd']] for k, v in t.items()])
print("\nndarray:")
print(result_nparra)
print("Type: ",type(result_nparra))


Original dictionary:
{'column0': {'a': 1, 'b': 0.0, 'c': 0.0, 'd': 2.0}, 'column1': {'a': 3.0, 'b': 1, 'c': 0.0, 'd': -1.0}, 'column2': {'a': 4, 'b': 1, 'c': 5.0, 'd': -1.0}, 'column3': {'a': 3.0, 'b': -1.0, 'c': -1.0, 'd': -1.0}}
Type:  <class 'dict'>

ndarray:
[[ 1.  0.  0.  2.]
 [ 3.  1.  0. -1.]
 [ 4.  1.  5. -1.]
 [ 3. -1. -1. -1.]]
Type:  <class 'numpy.ndarray'>


Q3. Write the Numpy program to find and store the non-zero unique
rows in an array after comparing each row with other row in the
given matrix?
 
    Original array-
    [[ 1 1 0]
    [ 0 0 0]
    [ 0 2 3]
    [ 0 0 0]
    [ 0 -1 1]
    [ 0 0 0]]
    Non-zero unique rows-
    [[ 1 1 0]
    [ 0 2 3]
    [ 0 -1 1]]

In [4]:
import numpy as np
arra = np.array([[ 1,  1,  0],
                 [ 0,  0,  0],
                 [ 0,  2,  3],
                 [ 0,  0,  0],
                 [ 0, -1,  1],
                 [ 0,  0,  0]])

print("Original array:")
print(arra)
temp = {(0, 0, 0)}
result = []
for idx, row in enumerate(map(tuple, arra)):
    if row not in temp:
        result.append(idx)
print("\nNon-zero unique rows:")
print(arra[result])

Original array:
[[ 1  1  0]
 [ 0  0  0]
 [ 0  2  3]
 [ 0  0  0]
 [ 0 -1  1]
 [ 0  0  0]]

Non-zero unique rows:
[[ 1  1  0]
 [ 0  2  3]
 [ 0 -1  1]]


Q4. Write the NumPy program to multiply the matrix by another matrix
of complex numbers and create a new matrix of complex
numbers?

    Sample outputFirst array-
    [ 1.+2.j 3.+4.j]
    Second array-
    [ 5.+6.j 7.+8.j]
    Product of above two arrays-
    (70-8j)

In [6]:
import numpy as np
x = np.array([1+2j,3+4j])
print("First array:")
print(x)
y = np.array([5+6j,7+8j])
print("Second array:")
print(y)
z = np.vdot(x, y)
print("Product of above two arrays:")
print(z)

First array:
[1.+2.j 3.+4.j]
Second array:
[5.+6.j 7.+8.j]
Product of above two arrays:
(70-8j)


Q5. Write a NumPy program to generate the matrix product of two
Arrays?

    Sample OutputMatrices and vectors.
    x-
    [[1, 0], [1, 1]]
    y-
    [[3, 1], [2, 2]]
    Matrix product of above two arrays-
    [[3 1]
    [5 3]]


In [7]:
import numpy as np
x = [[1, 0], [1, 1]]
y = [[3, 1], [2, 2]]
print("Matrices and vectors.")
print("x:")
print(x)
print("y:")
print(y)
print("Matrix product of above two arrays:")
print(np.matmul(x, y))


Matrices and vectors.
x:
[[1, 0], [1, 1]]
y:
[[3, 1], [2, 2]]
Matrix product of above two arrays:
[[3 1]
 [5 3]]


Q6. Write the NumPy program to find roots of the following
Polynomials?

    a) (x
    2
    - 4x + 7)
    b) x4
    - 11x3 + 9x2 + 11x ? 10
    Sample outputRoots of the first polynomial-
    [ 1. 1.]
    Roots of the second polynomial-
    [ 11.04461946+0.j -0.87114210+0.j 0.91326132+0.4531004j
    0.91326132-0.4531004j ]

In [8]:
import numpy as np
print("Roots of the first polynomial:")
print(np.roots([1, -2, 1]))
print("Roots of the second polynomial:")
print(np.roots([1, -12, 10, 7, -10]))


Roots of the first polynomial:
[1. 1.]
Roots of the second polynomial:
[11.04461946+0.j        -0.8711421 +0.j         0.91326132+0.4531004j
  0.91326132-0.4531004j]


Q7. Write the NumPy program to calculate inverse of sine, cosine,
and inverse tangent for all elements in a given array?

    Sample outputInverse sine- [-1.57079633 0. 1.57079633]
    Inverse cosine- [3.14159265 1.57079633 0. ]
    Inverse tangent- [-0.78539816 0. 0.78539816]

In [9]:
import numpy as np
x = np.array([-1., 0, 1.])
print("Inverse sine:", np.arcsin(x))
print("Inverse cosine:", np.arccos(x))
print("Inverse tangent:", np.arctan(x))

Inverse sine: [-1.57079633  0.          1.57079633]
Inverse cosine: [3.14159265 1.57079633 0.        ]
Inverse tangent: [-0.78539816  0.          0.78539816]


Q8. Write the NumPy program to calculate the difference between in
neighbouring elements, element-wise of a given array?

    Sample outputOriginal array-
    [1 3 5 7 0]
    Difference between neighbouring elements, element-wise of the said array-
    [ 2 2 2 -7]

In [11]:
import numpy as np
x = np.array([1, 3, 5, 7, 0])
print("Original array: ")
print(x)
r1 = np.ediff1d(x, to_begin=[0, 0], to_end=[200])
r2 = np.insert(np.append(np.diff(x), 200), 0, [0, 0])
assert np.array_equiv(r1, r2)
print("Difference between neighboring elements, element-wise, and prepend [0, 0] and append[100] to the said array:")
print(r2)

Original array: 
[1 3 5 7 0]
Difference between neighboring elements, element-wise, and prepend [0, 0] and append[100] to the said array:
[  0   0   2   2   2  -7 200]


Q9. Write the Python program to find the maximum and the minimum
value of a given flattened array?

    Expected OutputOriginal flattened array-
    [[0 1]
    [2 3]]
    Maximum value of the above flattened array3
    Minimum value of the above flattened array0

In [12]:
import numpy as np
a = np.arange(4).reshape((2,2))
print("Original flattened array:")
print(a)
print("Maximum value of the above flattened array:")
print(np.amax(a))
print("Minimum value of the above flattened array:")
print(np.amin(a))

Original flattened array:
[[0 1]
 [2 3]]
Maximum value of the above flattened array:
3
Minimum value of the above flattened array:
0


Q10. Write the NumPy program to calculate the difference between in
the maximum and the minimum values of a given array along the
second axis ?

    Expected OutputOriginal array-
    [[ 0 1 2 3 4 5]
    [ 6 7 8 9 10 11]]
    Difference between the maximum and the minimum values of the said array-
    [5 5]


In [13]:
import numpy as np
x = np.arange(12).reshape((2, 6))
print("\nOriginal array:")
print(x)
r1 = np.ptp(x, 1)
r2 = np.amax(x, 1) - np.amin(x, 1)
assert np.allclose(r1, r2)
print("\nDifference between the maximum and the minimum values of the said array:")
print(r1)


Original array:
[[ 0  1  2  3  4  5]
 [ 6  7  8  9 10 11]]

Difference between the maximum and the minimum values of the said array:
[5 5]


Q11. Write the NumPy program to compute the weighted of the given
array ?

    Sample OutputOriginal array-
    [0 1 2 3 4]
    Weighted average of the said array2.6666666666666665

In [14]:
import numpy as np
x = np.arange(5)
print("\nOriginal array:")
print(x)
weights = np.arange(1, 6)
r1 = np.average(x, weights=weights)
r2 = (x*(weights/weights.sum())).sum()
assert np.allclose(r1, r2)
print("\nWeighted average of the said array:")
print(r1)


Original array:
[0 1 2 3 4]

Weighted average of the said array:
2.6666666666666665


Q12. Write the NumPy program to compute the mean, standard
deviation, and the variance of a given array along the second
axis?

    Sample outputOriginal array-
    [0 1 2 3 4 5]
    Mean- 2.5
    std- 1
    variance- 2.9166666666666665

In [15]:
import numpy as np
x = np.arange(6)
print("\nOriginal array:")
print(x)
r1 = np.mean(x)
r2 = np.average(x)
assert np.allclose(r1, r2)
print("\nMean: ", r1)
r1 = np.std(x)
r2 = np.sqrt(np.mean((x - np.mean(x)) ** 2 ))
assert np.allclose(r1, r2)
print("\nstd: ", 1)
r1= np.var(x)
r2 = np.mean((x - np.mean(x)) ** 2 )
assert np.allclose(r1, r2)
print("\nvariance: ", r1)


Original array:
[0 1 2 3 4 5]

Mean:  2.5

std:  1

variance:  2.9166666666666665


Q13. Write the Numpy program to compute the covariance matrix of the
two given arrays?
    
    Sample OutputOriginal array1-
    [0 1 2]
    Original array1-
    [2 1 0]
    Covariance matrix of the said arrays-
    [[ 1. -1.]
    [-1. 1.]]

In [16]:
import numpy as np
x = np.array([0, 1, 2])
y = np.array([2, 1, 0])
print("\nOriginal array1:")
print(x)
print("\nOriginal array1:")
print(y)
print("\nCovariance matrix of the said arrays:\n",np.cov(x, y))


Original array1:
[0 1 2]

Original array1:
[2 1 0]

Covariance matrix of the said arrays:
 [[ 1. -1.]
 [-1.  1.]]


Q14. Write a NumPy program to compute the cross-correlation of two
given arrays ?

    Sample OutputOriginal array1-
    [0 1 3]
    Original array1-
    [2 4 5]
    Cross-correlation of the said arrays-
    [ [ 2.33333333 2.16666667 ]
     [ 2.16666667 2.33333333 ] ]

In [18]:
import numpy as np
x = np.array([0, 1, 3])
y = np.array([2, 4, 5])
print("\nOriginal array1:")
print(x)
print("\nOriginal array1:")
print(y)
print("\nCross-correlation of the said arrays:\n",np.cov(x, y))



Original array1:
[0 1 3]

Original array1:
[2 4 5]

Cross-correlation of the said arrays:
 [[2.33333333 2.16666667]
 [2.16666667 2.33333333]]


Q15. Write the NumPy program to compute Pearson product-moment
correlation coefficients of two given arrays?

    Sample OutputOriginal array1-
    [0 1 3]
    Original array1-
    [2 4 5]
    Pearson product-moment correlation coefficients of the said arrays-
    [[1. 0.92857143]
    [0.92857143 1. ]]

In [19]:
import numpy as np
x = np.array([0, 1, 3])
y = np.array([2, 4, 5])
print("\nOriginal array1:")
print(x)
print("\nOriginal array1:")
print(y)
print("\nPearson product-moment correlation coefficients of the said arrays:\n",np.corrcoef(x, y))



Original array1:
[0 1 3]

Original array1:
[2 4 5]

Pearson product-moment correlation coefficients of the said arrays:
 [[1.         0.92857143]
 [0.92857143 1.        ]]


Q16. Write the python program to count the number of occurrences of
each value in a given array of non-negative integers?
 
Note: bincount() Function- It count the occurrence of each value in an array of the
non- negative integers in the range of the array between the minimum and maximum values
including the values that did not occur.

    Sample OutputOriginal array-
    [0, 1, 6, 1, 4, 1, 2, 2, 7]
    Number of occurrences of each value in array-
    [1 3 2 0 1 0 1 1]

In [20]:
import numpy as np
array1 = [0, 1, 6, 1, 4, 1, 2, 2, 7] 
print("Original array:")
print(array1)
print("Number of occurrences of each value in array: ")
print(np.bincount(array1))


Original array:
[0, 1, 6, 1, 4, 1, 2, 2, 7]
Number of occurrences of each value in array: 
[1 3 2 0 1 0 1 1]


Q17. Write a Numpy program to compute the histogram of nums
against the bins?

    Sample Outputnums- [0.5 0.7 1. 1.2 1.3 2.1]
    P a g e 29 | 44
    bins- [0 1 2 3]
    Result- (array([2, 3, 1], dtype=int64), array([0, 1, 2, 3]))

In [21]:
import numpy as np
import matplotlib.pyplot as plt
nums = np.array([0.5, 0.7, 1.0, 1.2, 1.3, 2.1])
bins = np.array([0, 1, 2, 3])
print("nums: ",nums)
print("bins: ",bins)
print("Result:", np.histogram(nums, bins))
plt.hist(nums, bins=bins)
plt.show()

nums:  [0.5 0.7 1.  1.2 1.3 2.1]
bins:  [0 1 2 3]
Result: (array([2, 3, 1], dtype=int64), array([0, 1, 2, 3]))


<Figure size 640x480 with 1 Axes>

## Great Job!